"""
AUTO-BROKER: Governance Core Migration

Revision ID: 2026_02_15_governance_core
Revises: 
Create Date: 2026-02-15 10:00:00.000000

Crea tabelle per sistema governance asimmetrica:
- veto_sessions: Gestione stato veto window
- decision_audit: Audit trail GDPR-compliant
- operator_presence: Heartbeat operatori
- governance_config: Configurazione dinamica
- operatori: Tabella operatori (se non esiste)
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '2026_02_15_governance_core'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabella operatori (placeholder - verifica se esiste già)
    op.execute("""
        CREATE TABLE IF NOT EXISTS operatori (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            email VARCHAR(200) NOT NULL UNIQUE,
            name VARCHAR(200) NOT NULL,
            role VARCHAR(50) NOT NULL DEFAULT 'operator',
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    
    # Tabella veto_sessions
    op.create_table(
        'veto_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('agent_type', sa.Enum('PAOLO', 'GIULIA', name='agenttype'), nullable=False),
        sa.Column('operation_type', sa.String(50), nullable=False),
        sa.Column('shipment_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('carrier_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('dispute_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('amount_eur', sa.Numeric(10, 2), nullable=False),
        sa.Column('confidence_score', sa.Numeric(3, 2), nullable=True),
        sa.Column('status', sa.Enum('RESERVED', 'COMMITTING', 'COMMITTED', 'VETOED', 'EXPIRED', 'CANCELLED', name='vetostatus'), nullable=False),
        sa.Column('timeout_seconds', sa.Integer, nullable=False, server_default='60'),
        sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('vetoed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('operator_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('operator_rationale', sa.Text(), nullable=True),
        sa.Column('blockchain_tx_hash', sa.String(66), nullable=True),
        sa.Column('compensation_tx_hash', sa.String(66), nullable=True),
        sa.Column('context', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['carrier_id'], ['corrieri.id'], name='fk_veto_carrier'),
        sa.ForeignKeyConstraint(['operator_id'], ['operatori.id'], name='fk_veto_operator'),
        sa.ForeignKeyConstraint(['shipment_id'], ['spedizioni.id'], name='fk_veto_shipment'),
        sa.PrimaryKeyConstraint('id', name='pk_veto_sessions')
    )
    
    # Indici per veto_sessions
    op.create_index('idx_veto_status_expires', 'veto_sessions', ['status', 'expires_at'], unique=False)
    op.create_index('idx_veto_shipment', 'veto_sessions', ['shipment_id', 'created_at'], unique=False)
    op.create_index('idx_veto_agent_status', 'veto_sessions', ['agent_type', 'status'], unique=False)
    
    # Tabella decision_audit
    op.create_table(
        'decision_audit',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('veto_session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('event_type', sa.String(50), nullable=False),
        sa.Column('ai_rationale', postgresql.JSONB(), nullable=True),
        sa.Column('ai_model_version', sa.String(50), nullable=True),
        sa.Column('ai_confidence', sa.Numeric(3, 2), nullable=True),
        sa.Column('evidence_hashes', postgresql.JSONB(), nullable=False, server_default='[]'),
        sa.Column('operator_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('operator_action', sa.String(20), nullable=True),
        sa.Column('operator_rationale', sa.Text(), nullable=True),
        sa.Column('time_to_decision_ms', sa.Integer, nullable=True),
        sa.Column('final_state', sa.String(20), nullable=True),
        sa.Column('blockchain_tx_hash', sa.String(66), nullable=True),
        sa.Column('gdpr_article22_compliant', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('human_supervised', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('right_to_contest_noted', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('ipfs_audit_hash', sa.String(64), nullable=True),
        sa.ForeignKeyConstraint(['operator_id'], ['operatori.id'], name='fk_audit_operator'),
        sa.ForeignKeyConstraint(['veto_session_id'], ['veto_sessions.id'], name='fk_audit_session'),
        sa.PrimaryKeyConstraint('id', name='pk_decision_audit')
    )
    
    # Indici per decision_audit
    op.create_index('idx_audit_session_time', 'decision_audit', ['veto_session_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_operator', 'decision_audit', ['operator_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_event', 'decision_audit', ['event_type', 'timestamp'], unique=False)
    
    # Tabella operator_presence
    op.create_table(
        'operator_presence',
        sa.Column('operator_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('is_online', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
        sa.Column('dashboard_url', sa.String(500), nullable=True),
        sa.Column('current_session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('can_receive_urgent', sa.Boolean(), nullable=False, server_default='TRUE'),
        sa.Column('can_receive_standard', sa.Boolean(), nullable=False, server_default='TRUE'),
        sa.Column('user_agent', sa.String(200), nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['current_session_id'], ['veto_sessions.id'], name='fk_presence_session'),
        sa.ForeignKeyConstraint(['operator_id'], ['operatori.id'], name='fk_presence_operator'),
        sa.PrimaryKeyConstraint('operator_id', name='pk_operator_presence')
    )
    
    op.create_index('idx_presence_online', 'operator_presence', ['is_online'], unique=False)
    
    # Tabella governance_config
    op.create_table(
        'governance_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('environment', sa.String(20), nullable=False),
        sa.Column('governance_enabled', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('paolo_full_auto_max_eur', sa.Numeric(10, 2), nullable=False, server_default='5000.00'),
        sa.Column('paolo_hot_standby_max_eur', sa.Numeric(10, 2), nullable=False, server_default='10000.00'),
        sa.Column('paolo_human_in_loop_max_eur', sa.Numeric(10, 2), nullable=False, server_default='50000.00'),
        sa.Column('paolo_dual_control_min_eur', sa.Numeric(10, 2), nullable=False, server_default='50000.00'),
        sa.Column('paolo_veto_window_seconds', sa.Integer(), nullable=False, server_default='60'),
        sa.Column('paolo_escalation_first_reminder_seconds', sa.Integer(), nullable=False, server_default='15'),
        sa.Column('paolo_escalation_backup_seconds', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('giulia_full_auto_max_eur', sa.Numeric(10, 2), nullable=False, server_default='1000.00'),
        sa.Column('giulia_fast_track_confidence_min', sa.Numeric(3, 2), nullable=False, server_default='0.95'),
        sa.Column('giulia_fast_track_max_eur', sa.Numeric(10, 2), nullable=False, server_default='3000.00'),
        sa.Column('giulia_human_in_loop_max_eur', sa.Numeric(10, 2), nullable=False, server_default='10000.00'),
        sa.Column('giulia_standard_approval_hours', sa.Integer(), nullable=False, server_default='4'),
        sa.Column('giulia_escalation_senior_hours', sa.Integer(), nullable=False, server_default='24'),
        sa.Column('business_hours_start', sa.String(5), nullable=False, server_default='09:00'),
        sa.Column('business_hours_end', sa.String(5), nullable=False, server_default='18:00'),
        sa.Column('weekend_policy', sa.String(20), nullable=False, server_default='emergency_only'),
        sa.Column('holidays_policy', sa.String(20), nullable=False, server_default='human_in_loop_for_all'),
        sa.Column('max_dashboard_downtime_seconds', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('max_notification_downtime_seconds', sa.Integer(), nullable=False, server_default='60'),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['updated_by'], ['operatori.id'], name='fk_config_operator'),
        sa.PrimaryKeyConstraint('id', name='pk_governance_config'),
        sa.UniqueConstraint('environment', name='uq_config_environment')
    )
    
    # Inserisci config default
    op.execute("""
        INSERT INTO governance_config (environment, governance_enabled) 
        VALUES ('production', FALSE)
        ON CONFLICT (environment) DO NOTHING
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governance_config')
    op.drop_table('operator_presence')
    op.drop_table('decision_audit')
    op.drop_table('veto_sessions')
    op.drop_table('operatori')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS vetostatus")
    op.execute("DROP TYPE IF EXISTS agenttype")
    # ### end Alembic commands ###